function generateSvgPattern(pattern: {
  title: string;
  grid_data?: (string | number)[][] | null;
  color_palette?: { hex?: string; name?: string }[] | string[] | null;
  grid_size?: string | null;
  estimated_beads?: number | null;
  color_count?: number | null;
}): string {
  const grid = (pattern.grid_data || []) as string[][];
  if (!grid.length || !grid[0].length) return '';

  const rows = grid.length;
  const cols = grid[0].length;
  const cellSize = 16;
  const width = cols * cellSize;
  const height = rows * cellSize;
  const margin = 40;
  const headerHeight = 70;

  const palette = (pattern.color_palette || []) as Array<{ hex?: string; name?: string } | string>;
  const paletteMap = new Map<string, { hex: string; name?: string }>();
  for (const c of palette) {
    if (typeof c === 'string') paletteMap.set(c, { hex: c });
    else if (c && typeof c === 'object') {
      const hex = (c as { hex?: string }).hex || (c as { name?: string }).name || '#000000';
      paletteMap.set(hex, { hex, name: (c as { name?: string }).name });
    }
  }

  let cells = '';
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const color = grid[r][c] || '#ffffff';
      const safe = /^#[0-9a-fA-F]{3,6}$/.test(color) ? color : '#000000';
      cells += `    <rect x="${c * cellSize}" y="${r * cellSize}" width="${cellSize}" height="${cellSize}" fill="${safe}" stroke="#eeeeee" stroke-width="0.5" />\n`;
    }
  }

  let legendItems = '';
  let idx = 0;
  const swatchSize = 14;
  for (const [hex, info] of Array.from(paletteMap.entries())) {
    const x = (idx % 4) * 120;
    const y = Math.floor(idx / 4) * 24;
    legendItems += `    <rect x="${x}" y="${y}" width="${swatchSize}" height="${swatchSize}" fill="${info.hex}" stroke="#333" stroke-width="0.5" />\n`;
    legendItems += `    <text x="${x + swatchSize + 4}" y="${y + 11}" font-size="10" font-family="Arial, sans-serif">${info.name || hex}</text>\n`;
    idx++;
  }
  const legendRows = Math.ceil(paletteMap.size / 4);
  const legendHeight = Math.max(legendRows * 24, 0);

  const totalWidth = Math.max(width + margin * 2, 480);
  const totalHeight = headerHeight + height + margin + legendHeight + 30;

  const metaText = `Grid: ${pattern.grid_size || `${cols}x${rows}`} | Beads: ${pattern.estimated_beads || rows * cols} | Colors: ${pattern.color_count || paletteMap.size}`;

  return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${totalWidth}" height="${totalHeight}" viewBox="0 0 ${totalWidth} ${totalHeight}">\n  <rect width="100%" height="100%" fill="#ffffff"/>\n  <text x="${margin}" y="30" font-size="20" font-weight="bold" font-family="Arial, sans-serif">${escapeXml(pattern.title)}</text>\n  <text x="${margin}" y="55" font-size="11" fill="#555" font-family="Arial, sans-serif">${escapeXml(metaText)}</text>\n  <g transform="translate(${(totalWidth - width) / 2}, ${headerHeight})">\n${cells}  </g>\n  <g transform="translate(${margin}, ${headerHeight + height + margin})">\n${legendItems}  </g>\n  <text x="${margin}" y="${totalHeight - 10}" font-size="9" fill="#888" font-family="Arial, sans-serif">Generated by BeadPatternAI</text>\n</svg>\n`;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export { generateSvgPattern };
