export const PATTERN_IDEAS = [
  { title: 'Cute Panda', subject: 'panda', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'kawaii', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'kawaii', season: null },
  { title: 'Sleepy Cat', subject: 'cat', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Playful Dog', subject: 'dog', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Bunny Hop', subject: 'bunny', categories: ['animals'], collections: ['pocket-pets'], tags: ['animals', 'kawaii', 'easy', 'pixel-art'], difficulty: 'easy', style: 'kawaii', season: null },
  { title: 'Tiny Hamster', subject: 'hamster', categories: ['animals'], collections: ['pocket-pets'], tags: ['animals', 'kawaii', 'easy', 'pixel-art'], difficulty: 'easy', style: 'kawaii', season: null },
  { title: 'Red Fox', subject: 'fox', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Farm Cow', subject: 'cow', categories: ['animals'], collections: ['farm-friends'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Piggy Bank', subject: 'pig', categories: ['animals'], collections: ['farm-friends'], tags: ['animals', 'kawaii', 'easy', 'pixel-art'], difficulty: 'easy', style: 'kawaii', season: null },
  { title: 'Little Chick', subject: 'chick', categories: ['animals'], collections: ['farm-friends'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Ocean Whale', subject: 'whale', categories: ['animals'], collections: ['ocean-life'], tags: ['animals', 'nature', 'easy', 'pixel-art'], difficulty: 'easy', style: 'pixel-art', season: null },
  { title: 'Dolphin Jump', subject: 'dolphin', categories: ['animals'], collections: ['ocean-life'], tags: ['animals', 'nature', 'easy', 'pixel-art'], difficulty: 'easy', style: 'pixel-art', season: null },
  { title: 'Baby Turtle', subject: 'turtle', categories: ['animals'], collections: ['baby-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Safari Lion', subject: 'lion', categories: ['animals'], collections: ['safari'], tags: ['animals', 'medium', 'pixel-art'], difficulty: 'medium', style: 'pixel-art', season: null },
  { title: 'Giraffe Neck', subject: 'giraffe', categories: ['animals'], collections: ['safari'], tags: ['animals', 'medium', 'pixel-art'], difficulty: 'medium', style: 'pixel-art', season: null },
  { title: 'Koala Hug', subject: 'koala', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Hedgehog Roll', subject: 'hedgehog', categories: ['animals'], collections: ['pocket-pets'], tags: ['animals', 'kawaii', 'easy', 'pixel-art'], difficulty: 'easy', style: 'kawaii', season: null },
  { title: 'Penguin Waddle', subject: 'penguin', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Owl Hoot', subject: 'owl', categories: ['animals'], collections: ['cute-animals'], tags: ['animals', 'cute', 'easy', 'pixel-art'], difficulty: 'easy', style: 'cute', season: null },
  { title: 'Frog Prince', subject: 'frog', categories: ['animals', 'fantasy-mythical'], collections: ['fantasy-world'], tags: ['animals', 'fantasy', 'easy', 'pixel-art'], difficulty: 'easy', style: 'pixel-art', season: null },
  { title: 'Ladybug Dot', subject: 'ladybug', categories: ['animals'], collections: ['pocket-pets'], tags: ['animals', 'kawaii', 'easy', 'pixel-art'], difficulty: 'easy', style: 'kawaii', season: null },
];
